In [1]:
import numpy as np

## First part

In [2]:
# Read the puzzle, it contains a list of number and then 5x5 bingos
lines_raw = []
#with open('bingo_example.txt') as f:
with open('bingo.txt') as f:
    lines_raw = f.readlines()

lines = []
for indx, line in enumerate(lines_raw):
    if indx == 0:
        first_line = line.strip('\n')
    elif (indx - 1)%6 != 0:
        lines.append(line.split('\n')[0])

In [3]:
# Make a list of numbers from the first line
numbers = first_line.split(',')

#Transform strings to int
numbers = [int(i) for i in numbers]
print(numbers)

[28, 82, 77, 88, 95, 55, 62, 21, 99, 14, 30, 9, 97, 92, 94, 3, 60, 22, 18, 86, 78, 71, 61, 43, 79, 33, 65, 81, 26, 49, 47, 51, 0, 89, 57, 75, 42, 35, 80, 1, 46, 83, 39, 53, 40, 36, 54, 70, 76, 38, 50, 23, 67, 2, 20, 87, 37, 66, 84, 24, 98, 4, 7, 12, 44, 10, 29, 5, 48, 59, 32, 41, 90, 17, 56, 85, 96, 93, 27, 74, 45, 25, 15, 6, 69, 16, 19, 8, 31, 13, 64, 63, 34, 73, 58, 91, 11, 68, 72, 52]


In [4]:
# Make a list in which every element is a bingo of 5x5
n_bingos = len(lines)//5
bingos = [i for i in range(n_bingos)] 
bingo = np.ones((5,5))
for indx, line in enumerate(lines):
    n_bingo = indx//5
    a = [line[3*i:3*i+2].strip(' ') for i in range(5)]
    #print(line, a)
    bingo[indx%5, :] = a[:]

    bingos[n_bingo] = bingo
    if (indx!=0 and indx%5 == 4):
        bingo = np.ones((5,5))

print(n_bingos)
print(bingos[0])

100
[[31. 88. 71. 23. 61.]
 [ 4.  9. 14. 93. 51.]
 [52. 50.  6. 34. 55.]
 [70. 64. 78. 65. 95.]
 [12. 22. 41. 60. 57.]]


In [5]:
# Check each bingo how much it takes to win
count_last_win = len(numbers) # Maximum number of tries
for bingo_number, bingo in enumerate(bingos):
    win = False
    count = 0
    while not win and count_last_win > count:
        count += 1
        pool = set(numbers[:count])
        i = 0
        while not win and i < 5:
            #Check if bingo in the row or column
            row = set(bingo[i,:])
            col = set(bingo[:,i])
            if row.intersection(pool) == row or col.intersection(pool) == col:
                count_last_win = count
                bingo_last_win = bingo_number
                last_number = numbers[count-1]
                win = True 
            i += 1

print(f'BINGO {bingo_number} won after {count} numbers')
print(f'Last number: {last_number}')

BINGO 99 won after 25 numbers
Last number: 79


In [6]:
#The winner bingo is:
winner = bingos[bingo_last_win]

#sum all unmarked numbers in the winner bingo (make a set for that)
winner_set = set()
for i in range(5):
    winner_set.update(set(winner[i,:]))

suma = int(sum(winner_set - pool))
print( suma * last_number )

51034


## Second part

In [7]:
# Check each bingo how much it takes to win. 
# max_count is the number of tries for the bingo that wins latest
winners = []
max_count = 0
for bingo_number, bingo in enumerate(bingos):
    win = False
    count = 0
    while not win:
        count += 1
        pool = set(numbers[:count])
        i = 0
        while not win and i < 5:
            #Check if bingo in the row or column
            row = set(bingo[i,:])
            col = set(bingo[:,i])
            if row.intersection(pool) == row or col.intersection(pool) == col:
                winners.append(count)
                max_count = max(max_count, count)
                win = True
            i += 1

if (len(winners) != len(bingos)):
    print('ERROR WITH THE WINNERS LIST!')
            
last_number = numbers[max_count-1]
last_pool = set(numbers[:max_count])
print(' Position winners:')
print(winners)

print(f'\n Numbers taken for last winner: {max_count}')
print(numbers[:max_count])

print(f'\n Last number: {last_number}')

 Position winners:
[35, 70, 43, 33, 52, 53, 61, 72, 68, 51, 64, 48, 60, 61, 72, 68, 70, 43, 52, 42, 45, 87, 71, 67, 62, 62, 43, 62, 70, 52, 49, 54, 61, 62, 66, 44, 65, 35, 62, 43, 52, 69, 50, 25, 60, 60, 71, 41, 56, 75, 71, 76, 59, 61, 78, 64, 81, 77, 36, 60, 34, 57, 61, 61, 53, 62, 73, 44, 60, 78, 70, 53, 64, 72, 50, 56, 53, 37, 67, 67, 57, 49, 79, 41, 50, 77, 56, 78, 50, 44, 59, 63, 60, 55, 46, 35, 43, 73, 54, 70]

 Numbers taken for last winner: 87
[28, 82, 77, 88, 95, 55, 62, 21, 99, 14, 30, 9, 97, 92, 94, 3, 60, 22, 18, 86, 78, 71, 61, 43, 79, 33, 65, 81, 26, 49, 47, 51, 0, 89, 57, 75, 42, 35, 80, 1, 46, 83, 39, 53, 40, 36, 54, 70, 76, 38, 50, 23, 67, 2, 20, 87, 37, 66, 84, 24, 98, 4, 7, 12, 44, 10, 29, 5, 48, 59, 32, 41, 90, 17, 56, 85, 96, 93, 27, 74, 45, 25, 15, 6, 69, 16, 19]

 Last number: 19


In [8]:
# The loser bingo is the one that completes last (i.e., with the largest value in winners)
index_max = max(range(len(winners)), key=winners.__getitem__)
loser_bingo = bingos[index_max]
print('Loser bingo: ' + str(index_max))
print(loser_bingo)

Loser bingo: 21
[[33. 13. 84. 68. 72.]
 [92. 76.  1. 40. 19.]
 [86. 75. 34. 98. 82.]
 [ 8.  3.  4. 28.  0.]
 [91. 60. 27. 81. 39.]]


In [9]:
#sum all unmarked numbers in the winner bingo (make a set for that)
loser_set = set()
for i in range(5):
    loser_set.update(set(loser_bingo[i,:]))

suma = int(sum(loser_set - last_pool))
print( f'sum = {suma}' )
print( f'Answer = {suma * last_number}' )

sum = 286
Answer = 5434
