In [1]:
import numpy as np

## First part

In [2]:
# Read the puzzle, it contains a list of start and end points
lines_raw = []
#with open('vents_example.txt') as f:
with open('vents.txt') as f:
    lines_raw = f.readlines()

# Save start points and end points in p_is and p_fs
# Convert from strings to integers
pi_s = []
pf_s = []
for line in lines_raw:
    p1, p2 = line.strip(' ').split('->')
    pi = [int(i) for i in p1.split(',')]
    pf = [int(i) for i in p2.split(',')]
    pi_s.append(pi)
    pf_s.append(pf)
    
print(pi_s)
print(pf_s)

[[414, 379], [683, 947], [156, 577], [939, 503], [388, 907], [73, 572], [530, 157], [959, 896], [416, 698], [856, 281], [658, 767], [774, 799], [763, 833], [66, 314], [47, 984], [377, 52], [168, 935], [536, 778], [222, 919], [31, 419], [475, 232], [989, 980], [825, 237], [318, 896], [208, 57], [403, 796], [923, 937], [590, 827], [846, 416], [639, 221], [337, 554], [180, 121], [369, 402], [134, 857], [978, 957], [653, 75], [503, 391], [156, 392], [484, 231], [193, 302], [535, 145], [688, 629], [661, 85], [670, 765], [53, 892], [188, 893], [957, 127], [167, 309], [918, 611], [512, 286], [878, 434], [785, 546], [468, 278], [243, 181], [499, 734], [278, 72], [739, 672], [920, 147], [809, 232], [405, 349], [742, 228], [85, 543], [32, 181], [869, 693], [971, 444], [653, 950], [648, 174], [866, 310], [951, 145], [744, 447], [881, 570], [807, 217], [813, 554], [468, 651], [672, 989], [62, 644], [340, 263], [919, 513], [178, 272], [272, 419], [561, 188], [377, 169], [19, 240], [711, 756], [389,

In [3]:
# Make a grid of points, but first determine the furthermost corners

# Assign seed values using the first point
#x_min, x_max, y_min, y_max = pi_s[0][0], pi_s[0][0], pi_s[0][1], pi_s[0][1]
x_max, y_max = pi_s[0][0], pi_s[0][1]

zip_object = zip(pi_s, pf_s)
for pi, pf in zip_object:
#    x_min = min( x_min, pi[0], pf[0] )
    x_max = max( x_max, pi[0], pf[0] )
#    y_min = min( y_min, pi[1], pf[1] )
    y_max = max( y_max, pi[1], pf[1] )

#print(x_min, x_max)
#print(y_min, y_max)
print(x_max, y_max)

989 989


In [4]:
#positions = np.zeros( (x_max-x_min+1, y_max-y_min+1) )
positions = np.zeros( (x_max+1, y_max+1), dtype = np.uint32 )
zip_object = zip(pi_s, pf_s)
for pi, pf in zip_object:
    #Search for vertical lines
    if pi[0] == pf[0]:
        #create all the points in the segment
        x = pi[0] #- x_min
        yi = min(pi[1], pf[1])
        yf = max(pi[1], pf[1])
        for y in range(yi, yf+1):
            positions[y, x] += 1
            #print(pi, pf, x, y)

    #Search for horizontal lines
    elif pi[1] == pf[1]: 
        #create all the points in the segment
        y = pi[1] #- y_min
        xi = min(pi[0], pf[0])
        xf = max(pi[0], pf[0])
        for x in range(xi, xf+1):
            positions[y, x] += 1
            #print(pi, pf, x, y)

print(positions)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
#Check in which positions the value is > 1 (i.e, not 0 and not 1)
non_zeros = np.count_nonzero(positions)
ones = np.count_nonzero(positions == 1)
print('Answer: ' + str(non_zeros - ones) )

Answer: 6461


## Second part

In [6]:
#positions = np.zeros( (x_max-x_min+1, y_max-y_min+1) )
positions = np.zeros( (x_max+1, y_max+1), dtype = np.uint32 )
zip_object = zip(pi_s, pf_s)
for pi, pf in zip_object:
    #Search for vertical lines
    if pi[0] == pf[0]:
        #create all the points in the segment
        x = pi[0] #- x_min
        yi = min(pi[1], pf[1])
        yf = max(pi[1], pf[1])
        for y in range(yi, yf+1):
            positions[y, x] += 1
            #print(pi, pf, x, y)

    #Search for horizontal lines
    elif pi[1] == pf[1]: 
        #create all the points in the segment
        y = pi[1] #- y_min
        xi = min(pi[0], pf[0])
        xf = max(pi[0], pf[0])
        for x in range(xi, xf+1):
            positions[y, x] += 1
            #print(pi, pf, x, y)

    #Search for diagonal lines (Dy/Dx = +-1)
    elif abs( (pi[1]-pf[1])//(pi[0]-pf[0]) ) == 1: 
        #create all the points in the segment
        m = (pi[1]-pf[1])//(pi[0]-pf[0])
        x, y = pi[0], pi[1] #- y_min
        for i in range(abs(pi[1]-pf[1])+1):
            #print(x, y)
            positions[y, x] += 1
            #print(pi, pf, x, y)
            dx = (pf[0]-pi[0])//abs(pi[0]-pf[0])
            dy = (pf[1]-pi[1])//abs(pi[1]-pf[1])
            x += dx
            y += dy
            
print(positions)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [7]:
#Check in which positions the value is > 1 (i.e, not 0 and not 1)
non_zeros = np.count_nonzero(positions)
ones = np.count_nonzero(positions == 1)
print(f'Answer: {non_zeros - ones}')

Answer: 18065
