In [11]:
import numpy as np

## First part

In [84]:
# Read the puzzle: a heightmap with no separations 
A = np.genfromtxt('heightmap_example.txt', delimiter=1, dtype=int)
#A = np.genfromtxt('heightmap.txt', delimiter=1, dtype=int)
print(f'{A.shape = }') 
print(A)

A.shape = (5, 10)
[[2 1 9 9 9 4 3 2 1 0]
 [3 9 8 7 8 9 4 9 2 1]
 [9 8 5 6 7 8 9 8 9 2]
 [8 7 6 7 8 9 6 7 8 9]
 [9 8 9 9 9 6 5 6 7 8]]


In [85]:
# neighbours (nb) are in the horizontal or vertical direction
def locate_neighbours(i,j):
    '''Define the positions of the neighbours:'''
    # 1) in the four corners there are only 2 neighbours
    if i == 0 and j == 0: 
        nb_indices = [ (i, j+1), (i+1, j) ]
    elif i == 0 and j == m-1:
        nb_indices = [ (i, j-1), (i+1, j) ]
    elif i == n-1 and j == 0:
        nb_indices = [ (i, j+1), (i-1, j) ]
    elif i == n-1 and j == m-1:
        nb_indices = [ (i, j-1), (i-1, j) ]
    # 2) In the edges (but not corners) there are three neighbours
    elif i == 0:
        nb_indices = [ (i, j-1), (i, j+1), (i+1,j)]
    elif i == n-1:
        nb_indices = [ (i, j-1), (i, j+1), (i-1,j)]
    elif j == 0:
        nb_indices = [ (i, j+1), (i-1, j), (i+1,j)]
    elif j == m-1:
        nb_indices = [ (i, j-1), (i-1, j), (i+1,j)]
    else: #  if i != 0 and i != n-1 and j != 0 and j != m-1:
        nb_indices = [ (i, j-1), (i, j+1), (i-1, j), (i+1,j)]
    return(nb_indices)
        
# Now we search for the low points and store them in a list        
low_points = []
low_points_indices = []
n, m = A.shape
for i in range(n):
    for j in range(m):
        nb_indices = locate_neighbours(i,j)            
        nb_values = set()
        for pos in nb_indices:
            #print(A[pos[0],pos[1]])
            nb_values.add(A[pos[0],pos[1]])
        #print(nb_values)
        #print(f'{i=} {j=}  {A[i,j]=}  {nb_values=}')
        if A[i,j] < min(nb_values):
            low_points.append(A[i,j])
            low_points_indices.append([i,j])
        #print(f'{i =} {j=} {A[i,j] for i,j in range(i-1,i+2), range(j-1,j+2)}')
        #neighbours = set(A[i, j])
        #print(neighbours)
print(f'{low_points = }')

low_points = [1, 0, 5, 5]


In [86]:
#The risk level of a low point is 1 plus its height.
risk_level = len(low_points) + sum(low_points)
print(f'{risk_level = }')

# 1632 is too high!!! 

risk_level = 15


In [87]:
low_points_indices

[[0, 1], [0, 9], [2, 2], [4, 6]]

## Second part

It is too hard :( 